services:
  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    ports:
      - "8686:8686"
    env_file:
      - srv.env
    volumes:
      - ./services/lidarr/config:/config
      - ./data:/data
    networks:
      - qbtarrnet
