services:
  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    restart: unless-stopped
    ports:
      - "8686:8686"
    env_file:
      - srv.env
    volumes:
      - ./services/lidarr/config:/config
      - data:/data
    networks:
      - qbtarrnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lidarr.rule=PathPrefix(`/lidarr`)"
      - "traefik.http.routers.lidarr.entrypoints=http"
