services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    restart: unless-stopped
    env_file:
      - srv.env
    environment:
      WEBUI_PORTS: "8080/tcp,8080/udp"
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./services/qbittorrent/config:/config
      - data:/data
    networks:
      - qbtarrnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.entrypoints=http"
      - "traefik.http.routers.qbittorrent.rule=PathPrefix(`/`)"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
