services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    restart: unless-stopped
    env_file:
      - srv.env
    environment:
      WEBUI_PORTS: "8080/tcp,8080/udp"
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./services/qbittorrent/config:/config
      - data:/data
    networks:
      - qbtarrnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qb.entrypoints=http"
      - "traefik.http.routers.qb.rule=PathPrefix(`/qb`)"
      - "traefik.http.middlewares.qb_redirect.redirectregex.regex=^(.*)/qb$$"
      - "traefik.http.middlewares.qb_redirect.redirectregex.replacement=$$1/qb/"
      - "traefik.http.middlewares.qb_strip.stripprefix.prefixes=/qb/"
      # appropriate header changes
      - "traefik.http.middlewares.qb_headers.headers.customrequestheaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.middlewares.qb_headers.headers.customrequestheaders.Referer="
      - "traefik.http.middlewares.qb_headers.headers.customrequestheaders.Origin="
      - "traefik.http.routers.qb.middlewares=qb_strip,qb_redirect,qb_headers"
      # loadbalancer to *not* pass the host header
      - "traefik.http.services.qb.loadbalancer.server.port=8080"
      - "traefik.http.services.qb.loadbalancer.passhostheader=false"
