services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    env_file:
      - srv.env
    # environment:
    #   - LOG_LEVEL=debug
    ports:
      - 5055:5055
    volumes:
      - ./services/jellyseerr/config:/app/config
    networks:
      - qbtarrnet
