services:
  # for hotio images, a docker compose is provided at:
  # https://hotio.dev/containers/qbittorrent/#starting-the-container
  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    hostname: prowlarr
    restart: unless-stopped
    env_file:
      - ./hotio.env
    ports:
      - "9696:9696"
    volumes:
      - ./config/prowlarr:/config
    networks:
      - qbtarrnet

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    env_file:
      - ./hotio.env
    ports:
      - "8989:8989"
    volumes:
      - ./config/sonarr:/config
      - ./data:/data
    networks:
      - qbtarrnet

  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    env_file:
      - ./hotio.env
    ports:
      - "7878:7878"
    volumes:
      - ./config/radarr:/config
      - ./data:/data
    networks:
      - qbtarrnet

  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    ports:
      - "8686:8686"
    env_file:
      - ./hotio.env
    volumes:
      - ./config/lidarr:/config
      - ./data:/data
    networks:
      - qbtarrnet

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    restart: unless-stopped
    env_file:
      - ./hotio.env
    environment:
      WEBUI_PORTS: "8080/tcp,8080/udp"
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./config/qbt:/config
      - ./data:/data
    networks:
      - qbtarrnet

  mympd:
    image: ghcr.io/jcorporation/mympd/mympd:latest
    container_name: mympd
    # network_mode: "host"
    user: 1000:1000
    environment:
      - UMASK_SET=022
      - MYMPD_SSL=false
      - MYMPD_HTTP_PORT=8668
    ports:
      - "8668:8668"
    volumes:
      - /run/mpd/socket:/run/mpd/socket
      - ./mympd/data:/var/lib/mympd/
      - ./mympd/cachedir:/var/cache/mympd/
      - /media/music:/music/:ro
      - /var/lib/mpd/playlists:/playlists/:ro
    restart: unless-stopped
    networks:
      - dcsnet

  # using more or less the same configuration but the nginx container is not coming from hotio
  nginx:
    depends_on: 
      - prowlarr
      - sonarr
      - radarr
      - qbittorrent
      - mympd
    # restart: unless-stopped
    image: nginx
    container_name: nginx
    hostname: nginx
    env_file:
      - ./hotio.env
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./config/nginx/qbtarr.conf
        target: /etc/nginx/conf.d/00-qbtarr.conf
        read_only: true
    networks:
      - qbtarrnet

networks:
  qbtarrnet:
    name: qbtarrnet
  dcsnet:
    name: dcsnet
