services:
  mpd:
    image: qbtarr/mpd:alpine
    build:
      context: ./services/mpd
      args:
        MPD_VERSION: "0.23.15"
    container_name: mpd
    restart: unless-stopped
    env_file:
      - srv.env
    environment:
      - PIPEWIRE_RUNTIME_DIR=/var/run/pipewire
    ports:
      - "8000:8000"
      - "6600:6600"
    volumes:
      - ./services/mpd/config:/config
      - music:/music:ro
      - /var/run/pipewire/pipewire-0:/var/run/pipewire/pipewire-0
    ## To allow direct device access if no pipewire
    # devices:
    #  - /dev/snd
    networks:
      - dcsnet
    # healthcheck:
    #   test: nc -nz -w3 127.0.0.1 6600 || exit 1
    #   interval: 20s
    #   timeout: 5s
    #   retries: 3
