services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    env_file:
      - srv.env
    # environment:
    #   - TRANSMISSION_WEB_HOME=/transmission
    #   - USER= #optional
    #   - PASS= #optional
    #   - WHITELIST= #optional
    #   - PEERPORT= #optional
    #   - HOST_WHITELIST= #optional
    volumes:
      - ./services/transmission/config:/config
      - ./services/transmission/watch:/watch
      - /data/downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - qbtarrnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=PathPrefix(`/transmission`)"
      - "traefik.http.routers.transmission.entrypoints=http"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
