services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    env_file:
      - srv.env
    ports:
      - "32400:32400"
    volumes:
      - "./services/plex/config:/config"
      - "./services/plex/transcode:/transcode"
      - "data:/data:ro"
    networks:
      - qbtarrnet
