services:
  mympd:
    image: ghcr.io/jcorporation/mympd/mympd:latest
    container_name: mympd
    restart: unless-stopped
    # network_mode: "host"
    user: 1000:1000
    # IF one wants to use unix socket, enabled this one with the mpd healthcheck
    # to start the container only when mpd is ready
    # depends_on:
    #   mpd:
    #     condition: service_healthy
    environment:
      - UMASK_SET=022
      - MYMPD_SSL=false
      - MYMPD_HTTP_PORT=8668
      - MPD_HOST=mpd
      - MPD_PORT=6600
    ports:
      - "8668:8668"
    volumes:
      - ./services/mympd/data:/var/lib/mympd
      - ./services/mympd/cache:/var/cache/mympd
      - music:/music:ro
      - ./services/mpd/config/playlists:/playlists:ro
    networks:
      - dcsnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mympd.entrypoints=http"
      - "traefik.http.routers.mympd.rule=PathPrefix(`/mympd`)"
      - "traefik.http.middlewares.mympd_redirect.redirectregex.regex=^(.*)/mympd$$"
      - "traefik.http.middlewares.mympd_redirect.redirectregex.replacement=$$1/mympd/"
      - "traefik.http.middlewares.mympd_strip.stripprefix.prefixes=/mympd"
      # appropriate header changes
      - "traefik.http.middlewares.mympd_headers.headers.customrequestheaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.middlewares.mympd_headers.headers.customrequestheaders.Referer="
      - "traefik.http.middlewares.mympd_headers.headers.customrequestheaders.Origin="
      - "traefik.http.routers.mympd.middlewares=mympd_strip,mympd_redirect,mympd_headers"
      # loadbalancer to *not* pass the host header
      - "traefik.http.services.mympd.loadbalancer.server.port=8668"
      - "traefik.http.services.mympd.loadbalancer.passhostheader=false"
