services:
  traefik:
    image: traefik:v3
    container_name: traefik
    restart: unless-stopped
    env_file:
      - srv.env
    command:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--log.level=INFO"
      - "--entrypoints.http.address=:80"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--api.insecure=true"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8585:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - qbtarrnet
