services:
  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    env_file:
      - srv.env
    ports:
      - "7878:7878"
    volumes:
      - ./services/radarr/config:/config
      - data:/data
    networks:
      - qbtarrnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=PathPrefix(`/radarr`)"
      - "traefik.http.routers.radarr.entrypoints=http"
