services:
  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    env_file:
      - srv.env
    ports:
      - "8989:8989"
    volumes:
      - ./services/sonarr/config:/config
      - data:/data
    networks:
      - qbtarrnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=PathPrefix(`/sonarr`)"
      - "traefik.http.routers.sonarr.entrypoints=http"
